embeddings {
  tensor_name: "uf:09612"
  metadata_path: "09612/uf\\metadata.tsv"
  tensor_path: "09612/uf\\tensors.tsv"
}
embeddings {
  tensor_name: "koppen:09612"
  metadata_path: "09612/koppen\\metadata.tsv"
  tensor_path: "09612/koppen\\tensors.tsv"
}
embeddings {
  tensor_name: "biome:09612"
  metadata_path: "09612/biome\\metadata.tsv"
  tensor_path: "09612/biome\\tensors.tsv"
}
embeddings {
  tensor_name: "macroregion_name:09612"
  metadata_path: "09612/macroregion_name\\metadata.tsv"
  tensor_path: "09612/macroregion_name\\tensors.tsv"
}
